let animtaionData = [
  /*
    Fomat to add your details:
    
    {
        ContributorName: 'Your Name',
        ContributorURL: "Your Github Account Link",
        AnimationGif: 'Your Animation GIF file link',
        AnimationURL: "Your Animation Folder HTML file address",
    },
    */

  {
    ContributorName: "Gaurav Kedia",
    ContributorURL: "https://github.com/GauravMKedia",
    AnimationGif: "https://i.imgur.com/cA9gCiT.gif",
    AnimationURL:"./animations/Text-Animation/Bouncing_With_Reflection/Bouncing_Text.html",
  },
  {
    ContributorName: "Madhav Jha",
    ContributorURL: "https://github.com/jhamadhav",
    AnimationGif: "https://i.imgur.com/cwuZpqb.gif",
    AnimationURL: "./animations/Loader/Loading_Spinner/loading_spinner.html",
  },
  {
    ContributorName: "Harsheet Chordiya",
    ContributorURL: "https://github.com/Harsheet196",
    AnimationGif: "https://i.imgur.com/1Ez2kS4.gif",
    AnimationURL: "./animations/Loader/loading_sea-waves/index.html",
  },
  {
    ContributorName: "Harsh Zanwar",
    ContributorURL: "https://github.com/HarshZanwar2001",
    AnimationGif: "https://i.imgur.com/gRaPKAE.gif",
    AnimationURL: "./animations/hotcoffe/Hotcoffe.html",
  },
  {
    ContributorName: "Riya Loya",
    ContributorURL: "https://github.com/Riyaloya27",
    AnimationGif: "https://i.imgur.com/XFYVp5c.gif",
    AnimationURL: "./animations/growing_bars/growing_shrinking_bars.html",
  },
  {
    ContributorName: "Jasim Razi",
    ContributorURL: "https://github.com/jasimrazi",
    AnimationGif: "https://i.imgur.com/0c6Z3yf.gif",
    AnimationURL: "./animations/Loading_Animation/loadinganimation.html",
  },
  {
    ContributorName: "Khushi Shroff",
    ContributorURL: "https://github.com/Ks103",
    AnimationGif: "https://i.imgur.com/Hfyo0aR.gif",
    AnimationURL: "./animations/dragon_loader/index.html",
  },
  {
    ContributorName: "ImOnlyYisus",
    ContributorURL: "https://github.com/ImOnlyYisus",
    AnimationGif: "https://i.imgur.com/8RMAI4W.gif",
    AnimationURL: "./animations/social-menu/index.html",
  },
  {
    ContributorName: "Harsheet Chordiya",
    ContributorURL: "https://github.com/Harsheet196",
    AnimationGif: "https://i.imgur.com/NSZJJv2.gif",
    AnimationURL: "./animations/Loader/Homepage_Loader/index.html",
  },
  {
    ContributorName: "Riya Loya",
    ContributorURL: "https://github.com/Riyaloya27",
    AnimationGif: "https://i.imgur.com/IIdBmWB.gif",
    AnimationURL: "./animations/buttonanimation/button_animation.html",
  },
  {
    ContributorName: "Prathiksha Kini",
    ContributorURL: "https://github.com/pkini2002",
    AnimationGif: "https://i.imgur.com/vwLrRot.gif",
    AnimationURL: "./animations/shapeanimation/index.html",
  },
  {
    ContributorName: "Aryaman Shukla",
    ContributorURL: "https://github.com/AcidicArmadillo",
    AnimationGif: "https://i.imgur.com/i1TXGb0.gif",
    AnimationURL: "./animations/Truck-Animation/index.html",
  },
  {
    ContributorName: "Madhav Jha",
    ContributorURL: "https://github.com/jhamadhav",
    AnimationGif: "https://i.imgur.com/hAdWePY.gif",
    AnimationURL: "./animations/Loader/Loading_Bars/loading_bar.html",
  },
  {
    ContributorName: "Harsh Zanwar",
    ContributorURL: "https://github.com/HarshZanwar2001",
    AnimationGif: "https://i.imgur.com/tgr3lTy.gif",
    AnimationURL: "./animations/candle/candle.html",
  },
  {
    ContributorName: "Riya Loya",
    ContributorURL: "https://github.com/Riyaloya27",
    AnimationGif: "https://i.imgur.com/r8k8FrL.gif",
    AnimationURL: "./animations/coffee_machine/coffee_machine.html",
  },
  {
    ContributorName: "Riya Loya",
    ContributorURL: "https://github.com/Riyaloya27",
    AnimationGif: "https://i.imgur.com/uQVsIPH.gif",
    AnimationURL: "./animations/3D Toggle Switch/toggle_switch.html",
  },
  {
    ContributorName: "Vinni Fengade",
    ContributorURL: "https://github.com/VinniLP",
    AnimationGif: "https://i.imgur.com/KBfjstC.gif",
    AnimationURL: "./animations/Click_Me/click_me.html",
  },
  {
    ContributorName: "Pranav Mohgaonkar",
    ContributorURL: "https://github.com/gitPranav09",
    AnimationGif: "https://i.imgur.com/LaSlZRW.gif",
    AnimationURL: "./animations/simple_loader/simple_loader.html",
  },
  {
    ContributorName: "Pratik Agrawal",
    ContributorURL: "https://github.com/RudraPratik30",
    AnimationGif: "https://i.imgur.com/4q3JGMy.gif",
    AnimationURL: "./animations/Pratik Agrawal/animation-letters.html",
  },
  {
    ContributorName: "Pratik Agrawal",
    ContributorURL: "https://github.com/RudraPratik30",
    AnimationGif: "https://i.imgur.com/ihTfkR1.gif",
    AnimationURL: "./animations/Pratik Agrawal/Clock.html",
  },
  {
    ContributorName: "Arpit Agrawal",
    ContributorURL: "https://github.com/techie-arpit",
    AnimationGif: "https://i.imgur.com/lKB3yf2.gif",
    AnimationURL: "./animations/Arpit/Bird.html",
  },
  {
    ContributorName: "Smruti Agrawal",
    ContributorURL: "https://github.com/smritiagrawall",
    AnimationGif: "https://i.imgur.com/ZeQQNqx.gif",
    AnimationURL: "./animations/Smriti/tiger.html",
  },
  {
    ContributorName: "Arpit Agrawal",
    ContributorURL: "https://github.com/techie-arpit",
    AnimationGif: "https://i.imgur.com/5yBrYbh.gif",
    AnimationURL: "./animations/Rocket/Rocket.html",
  },
  {
    ContributorName: "Pratik Agrawal",
    ContributorURL: "https://github.com/RudraPratik30",
    AnimationGif: "https://i.imgur.com/LNU1mtR.gif",
    AnimationURL: "./animations/Flower-loader-1/Flower-loader-1.html",
  },
  {
    ContributorName: "Arpit Agrawal",
    ContributorURL: "https://github.com/techie-arpit",
    AnimationGif: "https://i.imgur.com/ewMT9UJ.gif",
    AnimationURL: "./animations/flower-loader-2/flower-loader-2.html",
  },
  {
    ContributorName: "Arpit Agrawal",
    ContributorURL: "https://github.com/techie-arpit",
    AnimationGif: "https://i.imgur.com/ZJzeGR5.gif",
    AnimationURL: "./animations/Ghost/ghost.html",
  },
  {
    ContributorName: "Pratik Agrawal",
    ContributorURL: "https://github.com/RudraPratik30",
    AnimationGif: "https://i.imgur.com/clA8zge.gif",
    AnimationURL: "./animations/Hen/hen.html",
  },
  {
    ContributorName: "Ritik Sharma",
    ContributorURL: "https://github.com/coder-ritik",
    AnimationGif: "https://i.imgur.com/MCtOmCn.gif",
    AnimationURL: "./animations/Pumpkin/pumpkin.html",
  },
  {
    ContributorName: "Shivansh Patel",
    ContributorURL: "https://github.com/patel-shivansh",
    AnimationGif: "https://i.imgur.com/cDW4bFV.gif",
    AnimationURL: "./animations/Cute-Cupcake/Cute-Cupcake.html",
  },
  {
    ContributorName: "Pratik Agrawal",
    ContributorURL: "https://github.com/RudraPratik30",
    AnimationGif: "https://i.imgur.com/XppZLWQ.gif",
    AnimationURL: "./animations/Cat/Cat.html",
  },
  {
    ContributorName: "Smruti Agrawal",
    ContributorURL: "https://github.com/smritiagrawall",
    AnimationGif: "https://i.imgur.com/YsqwKSS.gif",
    AnimationURL: "./animations/Atom/atom.html",
  },
  {
    ContributorName: "Arpit Agrawal",
    ContributorURL: "https://github.com/techie-arpit",
    AnimationGif: "https://i.imgur.com/Rb9PRQr.gif",
    AnimationURL: "./animations/Dogs/Dogs.html",
  },
  {
    ContributorName: "Shivansh Patel",
    ContributorURL: "https://github.com/patel-shivansh",
    AnimationGif: "https://i.imgur.com/Kw4b511.gif",
    AnimationURL: "./animations/SVG-letter/svg-letter.htm",
  },
  {
    ContributorName: "Ritik Sharma",
    ContributorURL: "https://github.com/coder-ritik",
    AnimationGif: "https://i.imgur.com/orGx8d2.gif",
    AnimationURL: "./animations/loader-1/loader-1.html",
  },
  {
    ContributorName: "Smruti Agrawal",
    ContributorURL: "https://github.com/smritiagrawall",
    AnimationGif: "https://i.imgur.com/GgXDdtm.gif",
    AnimationURL: "./animations/Paper-plane/paper-plane.html",
  },
  {
    ContributorName: "Gunali Rezqi Mauludi",
    ContributorURL: "https://github.com/gunalirezqimauludi",
    AnimationGif: "https://i.imgur.com/kubJGo7.gif",
    AnimationURL: "./animations/circle-wave/index.html",
  },
  {
    ContributorName: "Smruti Agrawal",
    ContributorURL: "https://github.com/smritiagrawall",
    AnimationGif: "https://i.imgur.com/KybO9t0.gif",
    AnimationURL: "./animations/Smriti/Hover.html",
  },
  {
    ContributorName: "Divyanshi Singh",
    ContributorURL: "https://github.com/Divyo-Singh",
    AnimationGif: "https://i.imgur.com/QK1G292.gif",
    AnimationURL: "./animations/code.divyo/code.divyo.html",
  },
  {
    ContributorName: "Ritik Sharma",
    ContributorURL: "https://github.com/coder-ritik",
    AnimationGif: "https://i.imgur.com/GoXOhHo.gif",
    AnimationURL: "./animations/Pigeon/pigeon.html",
  },
  {
    ContributorName: "Shivansh Patel",
    ContributorURL: "https://github.com/patel-shivansh",
    AnimationGif: "https://i.imgur.com/Lp1uMAI.gif",
    AnimationURL: "./animations/coffee-mug/coffee-mug.html",
  },
  {
    ContributorName: "Adithi Desai",
    ContributorURL: "https://github.com/AdithiDesai",
    AnimationGif: "https://i.imgur.com/4RW6QzD.gif",
    AnimationURL: "./animations/Cube/cubehtml.html",
  },
  {
    ContributorName: "Divyanshi Singh",
    ContributorURL: "https://github.com/Divyo-Singh",
    AnimationGif: "https://i.imgur.com/LWRYOvu.gif",
    AnimationURL: "./animations/water-heart <3/water-heart.html",
  },
  {
    ContributorName: "Ritik Sharma",
    ContributorURL: "https://github.com/coder-ritik",
    AnimationGif: "https://i.imgur.com/6LXslWv.gif",
    AnimationURL: "./animations/hey-card/hey-card.html",
  },
  {
    ContributorName: "Shivansh Patel",
    ContributorURL: "https://github.com/patel-shivansh",
    AnimationGif: "https://i.imgur.com/VwZ44CJ.gif",
    AnimationURL: "./animations/Coder/coder.html",
  },
  {
    ContributorName: "Harsheet Chordiya",
    ContributorURL: "https://github.com/Harsheet196",
    AnimationGif: "https://i.imgur.com/sbEtPlA.gif",
    AnimationURL: "./animations/Checker-Board_Reveal/main.html",
  },
  {
    ContributorName: "Harsheet Chordiya",
    ContributorURL: "https://github.com/Harsheet196",
    AnimationGif: "https://i.imgur.com/znlGDHi.gif",
    AnimationURL: "./animations/welcome_loader/main.html",
  },
  {
    ContributorName: "Divyanshi Singh",
    ContributorURL: "https://github.com/Divyo-Singh",
    AnimationGif: "https://i.imgur.com/CdBGoJo.gif",
    AnimationURL: "./animations/heart-ani/heart-ani.html",
  },
  {
    ContributorName: "Sarvesh Vyas",
    ContributorURL: "https://github.com/git-svyas",
    AnimationGif: "https://i.imgur.com/fiQZpws.gif",
    AnimationURL: "./animations/hourglass/hourglass.html",
  },
  {
    ContributorName: "Sarvesh Vyas",
    ContributorURL: "https://github.com/git-svyas",
    AnimationGif: "https://i.imgur.com/rv0R3wD.gif",
    AnimationURL: "./animations/shape_shifter/shape_shifter.html",
  },
  {
    ContributorName: "Pranav Mohgaonkar",
    ContributorURL: "https://github.com/gitPranav09",
    AnimationGif: "https://i.imgur.com/behqtxH.gif",
    AnimationURL: "./animations/bubble_background_animation/bubble_animation.html",
  },
  {
    ContributorName: "Divyanshi Singh",
    ContributorURL: "https://github.com/Divyo-Singh",
    AnimationGif: "https://i.imgur.com/uqwkUXN.gif",
    AnimationURL: "./animations/code_divyanshi/code_divyanshi.html",
  },
  {
    ContributorName: "Sarvesh Vyas",
    ContributorURL: "https://github.com/git-svyas",
    AnimationGif: "https://i.imgur.com/F9e4mc3.gif",
    AnimationURL: "./animations/sliding_load1/sliding_load1.html",
  },
  {
    ContributorName: "Sarvesh Vyas",
    ContributorURL: "https://github.com/git-svyas",
    AnimationGif: "https://i.imgur.com/RW6xXhY.gif",
    AnimationURL: "./animations/sliding_load2/sliding_load2.html",
  },
  {
    ContributorName: "Rohit Chandak",
    ContributorURL: "https://github.com/chandakrohit8",
    AnimationGif: "https://i.imgur.com/KfNbknv.gif",
    AnimationURL: "./animations/Glowing_Loader/glowing.html",
  },
  {
    ContributorName: "Rohit Chandak",
    ContributorURL: "https://github.com/chandakrohit8",
    AnimationGif: "https://i.imgur.com/OX5gWXl.gif",
    AnimationURL: "./animations/preloader/loader.html",
  },

];
